from flask import Blueprint, request, jsonify
import app.services.user_service as user_service
from app.middleware.verify_token import verify_token

user_bp = Blueprint('user_bp', __name__)

'''
API for creating a new user
This route expects the body to be:
{
  id, (the id must be the user UID generated by firebase auth)
  email,
  name,
  dob
}
'''
@user_bp.route('/', methods=["POST"])
# @verify_token
def create_user():
    response = user_service.create_user(request.json)
    return jsonify(response)

@user_bp.route('/', methods=["GET"])
@verify_token
def get():
    return 'Users'
